name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  Go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: Build
        run: go build -v ./core/...
      - name: Test
        run: go test ./core/... -v
